language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
sudo: false

matrix:
  fast_finish: true
  allow_failures:
  - python: "pypy3"

install:
  - pip install .

script: 
  - python setup.py test

notifications:
  email:
    on_success: change
    on_failure: change
